# Generated by Django 2.2.10 on 2021-04-09 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('avatar', models.ImageField(blank=True, upload_to='uploads/images/avatars/', verbose_name='Avatar')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('city', models.CharField(max_length=150, null=True, verbose_name='City')),
                ('organization', models.CharField(blank=True, max_length=150, verbose_name='Organization')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone Number')),
                ('timezone', timezone_field.fields.TimeZoneField(null=True, verbose_name='Time Zone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('zip_code', models.IntegerField(null=True, verbose_name='Zip Code')),
                ('nickname', models.CharField(max_length=150, null=True, verbose_name='Nickname')),
                ('age', models.IntegerField(choices=[(18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65)], null=True, verbose_name='Age')),
                ('type_user', models.CharField(choices=[('1', 'Client'), ('2', 'User Query'), ('3', 'Mechanic'), ('4', 'Pilot'), ('5', 'Technicnas')], default=1, max_length=15, verbose_name='Status')),
                ('activation_token', models.CharField(blank=True, max_length=40)),
                ('key_expires', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Country', verbose_name='Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
