# Generated by Django 2.2.10 on 2021-04-08 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_imei', models.BigIntegerField(verbose_name='Imei')),
                ('sim_phone', models.CharField(max_length=15, verbose_name='SIM Phone')),
                ('password', models.IntegerField(verbose_name='Password')),
                ('type_device', models.CharField(choices=[('GPS_Inside', 'GPS_Inside'), ('Arduino', 'Arduino')], max_length=15, verbose_name='Type Device')),
                ('model_device', models.CharField(choices=[('MDU001', 'MDU001'), ('MDU002', 'MDU002')], max_length=15, verbose_name='Model Device')),
                ('firmware_device', models.CharField(choices=[('MDU002_001', 'MDU002_001'), ('MDU002_002', 'MDU002_002'), ('MDU002_003', 'MDU002_003')], max_length=15, verbose_name='Firmware Device')),
                ('status', models.CharField(choices=[('0', 'Active'), ('1', 'Inactive')], max_length=15, verbose_name='Status')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Modified Date')),
                ('unit_id', models.IntegerField(blank=True, null=True, verbose_name='ID Unit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Devices',
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
