# Generated by Django 2.2.10 on 2021-04-08 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_type', models.CharField(max_length=15, verbose_name='Trace Type')),
                ('gps_date', models.DateField(null=True, verbose_name='Date GPS')),
                ('gps_time', models.TimeField(null=True, verbose_name='Time GPS')),
                ('date_recieved', models.DateTimeField(verbose_name='Time Received')),
                ('timestamp', models.CharField(blank=True, max_length=25, null=True, verbose_name='Tiemstamp')),
                ('geom', djgeojson.fields.PointField(blank=True, null=True, verbose_name='Coordinates')),
                ('gps_accuracy', models.IntegerField(blank=True, null=True, verbose_name='GPS Accuracy')),
                ('speed', models.FloatField(blank=True, null=True, verbose_name='Speed')),
                ('azimuth', models.CharField(blank=True, max_length=6, null=True, verbose_name='Azimuth')),
                ('odometer', models.FloatField(blank=True, null=True, verbose_name='Odometer')),
                ('ignition_time_count', models.IntegerField(blank=True, null=True, verbose_name='Ignition Time Count')),
                ('backup_battery', models.IntegerField(blank=True, null=True, verbose_name='Backup Battery')),
                ('orientation', models.IntegerField(blank=True, null=True, verbose_name='Orientation')),
                ('satellites_used', models.IntegerField(blank=True, null=True, verbose_name='Satellites Used')),
                ('satellites_seen', models.IntegerField(blank=True, null=True, verbose_name='Satellites Seen')),
                ('gprs_status', models.CharField(blank=True, max_length=1, null=True, verbose_name='GPRS Status')),
                ('ignition', models.IntegerField(blank=True, null=True, verbose_name='Ignition')),
                ('frame', models.CharField(blank=True, max_length=255, null=True, verbose_name='Frame')),
                ('altitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Altitude')),
                ('direction', models.TextField(blank=True, null=True, verbose_name='Direction')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Modified Date')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Traces',
                'verbose_name_plural': 'Traces',
            },
        ),
    ]
