# Generated by Django 2.2.10 on 2021-04-08 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=150, verbose_name='Nickname')),
                ('type', models.CharField(choices=[('TYPE01', 'TYPE01'), ('TYPE02', 'TYPE02'), ('TYPE03', 'TYPE03'), ('TYPE04', 'TYPE04')], max_length=150, verbose_name='Type')),
                ('category', models.CharField(choices=[('Electric', 'Electric'), ('Scooter', 'Scooter'), ('Motocross', 'Motocross'), ('Enduro', 'Enduro'), ('Trial', 'Trial'), ('Trail', 'Trail'), ('Cruiser', 'Cruiser'), ('Chopper', 'Chopper'), ('Great Tourism', 'Great Tourism'), ('Racer', 'Racer')], max_length=150, verbose_name='Category')),
                ('model', models.CharField(max_length=150, verbose_name='Model')),
                ('serie', models.CharField(max_length=150, verbose_name='Serie')),
                ('registration_number', models.CharField(max_length=150, verbose_name='Registration Number')),
                ('manufacturing_year', models.PositiveIntegerField(verbose_name='Manufacturing Year')),
                ('manufacturer', models.CharField(max_length=150, verbose_name='Manufacturer')),
                ('engines_type', models.CharField(choices=[('Single Cylinder', 'Single Cylinder'), ('Two Cylinder', 'Two Cylinder'), ('Three Cylinder', 'Three Cylinder'), ('Tetra Cylindrical', 'Tetra Cylindrical')], max_length=150, verbose_name='Engines Type')),
                ('engines_models', models.CharField(max_length=150, verbose_name='Engines Model')),
                ('fuel_type', models.CharField(choices=[('FULL_TYPE01', 'FULL_TYPE01'), ('FULL_TYPE02', 'FULL_TYPE02'), ('FULL_TYPE03', 'FULL_TYPE03'), ('FULL_TYPE04', 'FULL_TYPE04')], max_length=150, verbose_name='Fuel Type')),
                ('fuel_capacity', models.PositiveIntegerField(verbose_name='Fuel Capacity')),
                ('fuel_autonomy', models.PositiveIntegerField(verbose_name='Fuel Autonomy')),
                ('number_seats', models.PositiveIntegerField(verbose_name='Number Seats')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('0', 'Inactive'), ('1', 'Active')], max_length=150, verbose_name='Status')),
                ('status_dry', models.CharField(choices=[('Ign OFF', 'Ign OFF'), ('Ign ON', 'Ign ON'), ('Driving', 'Driving'), ('W/o Coverage', 'W/o Coverage')], default='Ign OFF', max_length=150, verbose_name='Status Drive')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Modified Date')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Client')),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.Device', verbose_name='Devices')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
    ]
