# Generated by Django 3.2.3 on 2021-06-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20210609_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='engine_model',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Engines Model'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='engine_type',
            field=models.CharField(blank=True, choices=[('Single Cylinder', 'Single Cylinder'), ('Two Cylinder', 'Two Cylinder'), ('Three Cylinder', 'Three Cylinder'), ('Tetra Cylindrical', 'Tetra Cylindrical')], max_length=150, null=True, verbose_name='Engines Type'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='fuel_autonomy',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fuel Autonomy'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='fuel_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fuel Capacity'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('FULL_TYPE01', 'FULL_TYPE01'), ('FULL_TYPE02', 'FULL_TYPE02'), ('FULL_TYPE03', 'FULL_TYPE03'), ('FULL_TYPE04', 'FULL_TYPE04')], max_length=150, null=True, verbose_name='Fuel Type'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='manufacturing_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Manufacturing Year'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='model',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='number_seats',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number Seats'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='registration_number',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='serie',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='status_dry',
            field=models.CharField(blank=True, choices=[('Ign OFF', 'Ign OFF'), ('Ign ON', 'Ign ON'), ('Driving', 'Driving'), ('W/o Coverage', 'W/o Coverage')], default='Ign OFF', max_length=150, null=True, verbose_name='Status Drive'),
        ),
    ]
