# Generated by Django 3.2.3 on 2021-06-15 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
        ('devices', '0002_alter_device_options'),
        ('vehicles', '0004_alter_vehicles_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVehicles',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nickname', models.CharField(max_length=150, verbose_name='Nickname')),
                ('type', models.CharField(choices=[('TYPE01', 'TYPE01'), ('TYPE02', 'TYPE02'), ('TYPE03', 'TYPE03'), ('TYPE04', 'TYPE04')], max_length=150, verbose_name='Type')),
                ('category', models.CharField(choices=[('Electric', 'Electric'), ('Scooter', 'Scooter'), ('Motocross', 'Motocross'), ('Enduro', 'Enduro'), ('Trial', 'Trial'), ('Trail', 'Trail'), ('Cruiser', 'Cruiser'), ('Chopper', 'Chopper'), ('Great Tourism', 'Great Tourism'), ('Racer', 'Racer')], max_length=150, verbose_name='Category')),
                ('model', models.CharField(blank=True, max_length=150, null=True, verbose_name='Model')),
                ('serie', models.CharField(blank=True, max_length=150, null=True, verbose_name='Serie')),
                ('registration_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Registration Number')),
                ('manufacturing_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Manufacturing Year')),
                ('manufacturer', models.CharField(blank=True, max_length=150, null=True, verbose_name='Manufacturer')),
                ('engine_type', models.CharField(blank=True, choices=[('Single Cylinder', 'Single Cylinder'), ('Two Cylinder', 'Two Cylinder'), ('Three Cylinder', 'Three Cylinder'), ('Tetra Cylindrical', 'Tetra Cylindrical')], max_length=150, null=True, verbose_name='Engines Type')),
                ('engine_model', models.CharField(blank=True, max_length=150, null=True, verbose_name='Engines Model')),
                ('fuel_type', models.CharField(blank=True, choices=[('FULL_TYPE01', 'FULL_TYPE01'), ('FULL_TYPE02', 'FULL_TYPE02'), ('FULL_TYPE03', 'FULL_TYPE03'), ('FULL_TYPE04', 'FULL_TYPE04')], max_length=150, null=True, verbose_name='Fuel Type')),
                ('fuel_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fuel Capacity')),
                ('fuel_autonomy', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fuel Autonomy')),
                ('number_seats', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number Seats')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('status_dry', models.CharField(blank=True, choices=[('Ign OFF', 'Ign OFF'), ('Ign ON', 'Ign ON'), ('Driving', 'Driving'), ('W/o Coverage', 'W/o Coverage')], default='Ign OFF', max_length=150, null=True, verbose_name='Status Drive')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Modified Date')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.client', verbose_name='Client')),
                ('device', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='devices.device', verbose_name='Devices')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Vehicle',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
