# Generated by Django 2.2.10 on 2021-04-08 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclesGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=150, verbose_name='Nickname')),
                ('description', models.TextField(verbose_name='Description')),
                ('color', models.CharField(blank=True, max_length=150, verbose_name='Color')),
                ('status', models.CharField(choices=[('0', 'Inactive'), ('1', 'Active')], max_length=150, verbose_name='Status')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Modified Date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('vehicles', models.ManyToManyField(blank=True, to='vehicles.Vehicles', verbose_name='Vehicles')),
            ],
            options={
                'verbose_name': 'Bike Group',
                'verbose_name_plural': 'Bike Groups',
            },
        ),
    ]
