# Generated by Django 3.2 on 2021-04-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclesgroup',
            options={'verbose_name': 'Vehicle Group', 'verbose_name_plural': 'Vehicle Groups'},
        ),
    ]
